# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV"
    url = "https://drive.google.com/file/d/1wLw7seqUjZUY0sXKAqJV8yG8S7vcI18k/view?usp=sharing"
    weight = 70
    
 [[main]]
    name = "Linkedln"
    url = "https://www.linkedin.com/in/danny-vu-b84562191/"
    weight = 70
    
 [[main]]
    name = "Project"
    url = "project/"
    weight = 70
    
  [[main]]
    name = "Phase 1"
    url = "phase1/"
    weight = 80
    
  [[main]]
    name = "Phase 2"
    url = "phase2/"
    weight = 90  
    
  [[main]]
    name = "Phase 3"
    url = "phase3/"
    weight = 100
